Private event:first draft
ioilmio/event-app pull request #1
Opened 2020-07-27 22:48 UTC by ioilmio

This is a request for a code review:
What i'm doing right and what wrong?
Where i have to improve?
Are my models,controllers and associations correct?
Any suggestions will be warmly welcome

Thank you

2020-07-27 22:52 UTC, ioilmio commented
I just noticed my checks are not running, is the file correct?

2020-07-28 05:14 UTC, euqueme requested changes
> ### Pull Request reviewed by Maria Eugenia Queme P. (TSE)

### Hello @ioilmio :lollipop: 

### Thank you for your submission :handshake: this is good, start your project runs and some pages are loading but we still have to make some important features work so let's get to it :construction: :construction_worker: 

#### Behaviour

* [ ] It has functional `login` page (authentication WITHOUT password, just providing a user email) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/login_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

- Please fix your logging page so it's possible to sign and login a user right now it looks like this:
![image](https://user-images.githubusercontent.com/52209067/88615550-6abd3500-d04f-11ea-85a6-37325288f4a1.png)

* [ ] Logged in user can create new event  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_can_create_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] Event's index page displays past and upcoming events lists ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] The event's show page displays the list of attendants ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/events_attendees_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] The user's show page displays events the user has created and events that the user is attending to separated in past and upcoming ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] Navigation links are present at the top of the page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/navigation_links_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

#### Associations

- [x] I've left comments directly in your modes code where changes have to be made in your associations

#### Migrations

- [x] I've left comments directly in your migration files where changes have to be made 

#### Controllers

- [x] I've left comments directly in your controllers where changes have to be made

#### Database foreign keys and indexes ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/foreign_key_index_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))

There are a few ways to add foreign keys for association in migrations. You can:

* use `t.references` with index option https://api.rubyonrails.org/v5.1.7/classes/ActiveRecord/ConnectionAdapters/TableDefinition.html#method-i-references
* use `t.belongs_to` (alias for `references`) with index option https://api.rubyonrails.org/v5.1.7/classes/ActiveRecord/ConnectionAdapters/TableDefinition.html#method-i-belongs_to
* create integer field and corresponding index manually, e.g.

```ruby
def change
  create_table :events do |t|
    t.integer :creator_id
  end

  add_index :events, :creator_id
end
```

Whichever path you choose, the final result should be a database schema similar to:

* [x] the events table has column `creator_id` of type `integer`
* [x] an index for `creator_id` column is added
* [x] the attendances table has column `event_id` of type `integer`
* [x] an index for `event_id` column is added
* [x] the attendances table has column `user_id` of type `integer`
* [x] an index for `user_id` column is added

Why indices for foreign keys are necessary? In short: Since the foreign key columns will be used often to retrieve related information, it's important to index them (queries on those columns will be faster with indexes). More details:

* https://semaphoreci.com/blog/2017/05/09/faster-rails-is-your-database-properly-indexed.html
* https://sqlperformance.com/2012/11/t-sql-queries/benefits-indexing-foreign-keys.

#### Tests

* [ ] models have unit tests for validations and associations (Rspec) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
* [ ] authentication have has integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
* [ ] event managment features have integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))

- Your test cases aren't passing let's fix them

![image](https://user-images.githubusercontent.com/52209067/88621530-ee7e1e00-d05d-11ea-82ce-fa66866402ee.png)

#### General

##### Readme

- [ ] Your readme file is just a template and currently doesn't have any information about your project let's fix it.

##### Stickler and linters

- [ ] you are missing the .stickler.yml file and your project needs to be activated in [stickler](https://stickler-ci.com/)

### That's it! :raised_hands: 

### Please :pray: do the changes :technologist: and submit for a code review when you are done :memo: 

Happy coding! :rocket: 

Any questions? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

2020-07-28 05:14 UTC, euqueme commented on app/models/user.rb
> +  has_many :events, dependent: :destroy
- [x] User model: `has_many :events, foreign_key: :creator_id` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_assoc_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

- instead of having the default user_id in the Events entity let's use the creator_id alias

2020-07-28 05:14 UTC, euqueme commented on app/models/event.rb
> +  belongs_to :user
- [x] Event model `belongs_to :creator, class_name: "User"` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_assoc_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

- instead of having the default user_id in the Events entity let's use the creator_id alias

2020-07-28 05:14 UTC, euqueme commented on db/migrate/20200727182232_create_events.rb
> +end
Migrations

* [x] events table has creator_id as the foreign key ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_assoc_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

2020-07-28 05:14 UTC, euqueme commented on app/controllers/events_controller.rb
> +  end
###### `create` action

* [x] uses #build method on association, i.e. `current_user.events.build(event_params)` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/build_method_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

2020-07-28 05:14 UTC, euqueme commented on app/controllers/events_controller.rb
> +  end
###### `index` action

* [x] lists past events, i.e. `@past_events = Event.previous_events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [x] lists ucomping events, i.e. `@upcoming_events = Event.upcoming_events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

2020-07-28 05:14 UTC, euqueme commented on app/controllers/users_controller.rb
> +  end
###### `show` action

* [ ] lists events created by user, i.e. `@created_events = current_user.events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/current_user_show_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] lists events previoulsy attendented by user **using event model scope**, i.e. `@past_events = current_user.attended_events.previous` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] lists upcoming events previously attended by user **using event model scope**, i.e. `@upcoming_events = current_user.attended_events.upcoming` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

2020-07-30 22:29 UTC, kobiyoyo requested changes
## Hi Team    ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are a few more things required. 
### General
- [x] Lets activate stickler 
* [x] Event's index page displays past and upcoming events lists
* [x] The event's show page displays the list of attendants 
* [x] The user's show page displays events the user has created and events that the user is attending to separated in past and upcoming 
- [x] Check comments below
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-07-30 22:29 UTC, kobiyoyo commented on app/controllers/events_controller.rb
> +    @upcoming_events = Event.upcoming_events
This should be in `index` method above.

2020-07-30 22:29 UTC, kobiyoyo commented on app/controllers/events_controller.rb
> +  end
````ruby
  def create
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to(events_path, notice: 'Event was successfully created')
    else
      flash.now[:alert] = "Event wasnt created"
      render :new
    end
  end
`````

2020-08-11 00:42 UTC, Ispirett requested changes
Status Changes required

Great job folks with all the changes made. :+1:  :+1: 

There is just one issue, Stickler is not activated on the repo. Please work on this.

2020-08-12 01:20 UTC, stratospherique approved these changes
### Great work implementing the suggested changes :clap: Congrats, the project is approved :heavy_check_mark: You may merge :+1: :+1: 

Keep up the good work :muscle: 
**_Ahmed Mahfoudh_**

2020-08-12 16:07 UTC, merged